# Generated by Django 3.2.12 on 2023-07-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0002_auto_20230529_0927"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="reviewed",
            new_name="ready_for_review",
        ),
    ]
