# Generated by Django 4.2.3 on 2023-09-02 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0003_rename_reviewed_review_ready_for_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="last_review_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="review",
            name="next_review_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
