# Generated by Django 4.2.3 on 2023-09-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0004_alter_review_last_review_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="exponential_time",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="review",
            name="next_review_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
