# Generated by Django 4.2.3 on 2023-09-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0005_review_exponential_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="hiragana",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="review",
            name="last_review_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="next_review_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
