# Generated by Django 4.2.3 on 2023-09-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0006_alter_flashcard_hiragana_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="next_review_date",
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True)),
        ),
    ]
