# Generated by Django 4.2.3 on 2023-09-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0007_alter_review_next_review_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="next_review_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
