# Generated by Django 4.2.3 on 2023-09-29 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0008_alter_review_next_review_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="last_review_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 29, 9, 50, 50, 520297, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="next_review_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 29, 9, 50, 50, 520310, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
