# Generated by Django 4.2.3 on 2023-12-28 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flashcards",
            "0010_flashcard_image_flashcard_story_flashcard_surname_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="image",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="story",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="last_review_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 28, 13, 25, 1, 57660, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="next_review_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 28, 13, 25, 1, 57672, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
