# Generated by Django 4.2.3 on 2024-05-16 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0012_alter_review_last_review_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="exponential_increment",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="last_review_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 16, 14, 43, 27, 299218, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="next_review_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 16, 14, 43, 27, 299218, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
