# Generated by Django 4.2.3 on 2024-05-17 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0013_review_exponential_increment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="was_wrong",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="last_review_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 17, 8, 17, 50, 938606, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="next_review_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 17, 8, 17, 50, 938606, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
